 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: mysql
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: mysql
   template:
     metadata:
       labels:
         app: mysql
     spec:
       containers:
       - name: mysql
         image: mysql:latest
         env:
         - name: MYSQL_DATABASE
           value: hackernews
         - name: MYSQL_ROOT_PASSWORD
           value:  dbpass
         resources:
           limits:
             memory: "512Mi"
             cpu: "500m"
         ports:
         - containerPort: 3306

 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      initContainers:
            - name: init-mysql
              image: busybox
              command: ['sh', '-c', 'until nslookup mysql-service; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: graphql
        image: mkallali/go-graphql-app:1.0.1
        env:
        - name: DB_HOST
          value: mysql-service
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306


---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  type: LoadBalancer
  selector:
    app: graphql
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080

      
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: graphql
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graphql
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

