pipeline {
  agent any
  stages {
stage('Validation') {
steps {
        //Moving in to the directory to execute the commands
        dir('deploy') {
            script {
                //Using the git command to check the difference between previous successful commit. ${GIT_PREVIOUS_SUCCESSFUL_COMMIT} is an environment variable comes with GIT Jenkins plugin
                //There is a drawback though, if it is the first time you are running this job, this variable is not available and fails the build
                //For the first time i had to use ${env.GIT_COMMIT} itself at both places to pass the build. A hack but worth it for future builds.

                def strCount = sh(returnStdout: true, script: "git diff --name-only ${env.GIT_COMMIT} ${GIT_PREVIOUS_SUCCESSFUL_COMMIT} | grep servicelayer | wc -l").trim()
                if(strCount=="0") {
                    echo "Skipping build no files updated"
                    CONTINUE_BUILD = false
                } else {
                    echo "Changes found in the servicelayer module"
                }
            }
        }
    }
    }
    stage('Upload CFN Template') {
      steps {
           dir('deploy') {
        sh 'echo "TEST PIPELINE"'
        sh '''
                pwd
                cd roles/cloudformation/files/
                aws --region us-east-2 cloudformation package \
                --template-file eks-root.json --output-template /tmp/packed-eks-stacks.json \
                --s3-bucket mkallali-eks-cfn-us-east-2 --use-json
                 '''
      }
      }
    }

 stage('Create Infra') {
           steps {
                dir('deploy') {
        sh 'echo "DEPLOY CFN "'
        sh '''
                pwd
                ansible-playbook eks-cluster.yml
            '''
      }
      }

 }

    }
}
